name: Go CI

on:
  push:         # run on every push
    branches: ["main"]
  pull_request: # also run on pull requests
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # adjust to your Go version

      - name: Download dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./... -v
